### PR TITLE
Enhanced version

### PR DESCRIPTION
**Pull request by lcipolina**
Hi! congratulations for your code. It has been very useful to me. 
Since I am actually using it a lot, I did some improvements that I hope you'd like. Entirely up to you.

1. Created a class to handle all functions
2. Added comments
3. Added a visualization of the output

cheers!

### CODE REVIEW

**Comment by Null3rror** [comment]
Hi! I'm glad my code helped you out :)
thanks for the improvements.

**Comment by lcipolina** [comment]
One question if you don't mind.

Why the meshgrid goes specifically from -1 to 1 ?

This line:

`np.linspace(-1.0, 1.0, num=r, endpoint=True)`

Thanks!

**Comment by Null3rror** [comment]
Hi sorry for answering late.
I chose r1 and r2 to be less than 1(r1 = 0.2 and r2 = 0.9 gave me the best results).
when applying ```ln(z/r1)``` transformation, we checked that ```if r1 <= |z| <= r2, we apply ln(z/r1) else 0```.
that's why i wanted |z| to be close to r1 and r2, so  ```np.linspace(-1.0, 1.0, num=r, endpoint=True)```.

**Comment by Null3rror** [comment]
I've decided to change the code for improvements, I'll create a new branch and will upload it there.
I'll be happy if you check it out.

**Comment by lcipolina** [comment]
Hi, thank you very much for your explanations. The code is working fine as it is now. 

If you want to spend some more time on it, these are the improvements I've made on my own code:

1. **LogTransform(.**) and **ExpTransform(.)** are not really needed. You can just use: **np.log(Z)** and **np.exp(Z)** as Python applies the operation to every element (you can try it yourself). This will not make a major change, but will improve the computation time. And it's just one liner.

2. This function: recreateImage(.) it's great to visualize what's going on and it provides an intuitive way of thinking about this. In reality, people use this other pre-built-function: "remap" https://docs.opencv.org/3.4/d1/da0/tutorial_remap.html

The remap function will "complete the pixels" in the sense that it will interpolate the missing pixels from the original plane to the transformed plane. So it's basucally your "recreate image" + an interpolator. This changes dramatically the result of the image, as it makes it less pixelated. HOWEVER, the remap function is really bitchy. The way OpenCV has implemented it, it's really backwards. So I am just letting you know it exists and its capabilities, but it's a dark tunnel to go to.

The remap function works "backwards". It starts from the final plane and applies the *reverse operation* to find the pixel coordinates. There are forums and forums about it's akward logic.

Apart from that, your code it's good and I see that it has been copied over the internet!

**Comment by Null3rror** [comment]
Hi I've added the new codes(in a another branch). 
Thanks for the suggestion, I'll def try them out.
If you want I can add you as a Collaborator so you can change the codes too?

**Comment by lcipolina** [comment]
Hi, hi, yes, the code is much better now!

 As for the collaboration, this is really up to you. I will be happy to whatever decision you take. 
One option is to keep working as we are now, which is, I do a pull request and then you review and accept/decline or you can make me a collaborator and I can change the code. 

I took your code as an inspiration for another thing I had to do, but customized it a little bit for my needs. It all depends on the user case, meaning which direction you want to give it to your code depending on what your needs are. In my case, I didn't have a circular picture, so I removed the (r1, r2) story. In the process, I've used your code to understand the logic of the droste effect.

I am working directly with Escher's Print Gallery, so the principle is the same (LOG-ROTATE-EXP) but the coefficients are a little bit different for me. So I took your code as inspiration and customized it to my needs.

**Pull request merged**
